# Purpose: This stack creates Cloudfront distribution in front of the S3 static site used for the LifeShield Documentation
# This distributions are protected by a Web WAF.
#
# NOTE: Deploy this template on us-east-1 in order to ease with ACM certificate provisioning for the stack
#
AWSTemplateFormatVersion: '2010-09-09'
Description: v0.2.0 CloudFront Web Distributions for LifeShield Documentation
Parameters:
  parPodId:
    Description: Pod domain name used as the key to query CMDB parameters
    Type: String
    Default: docs.icumed-lifeshield.com
  parHostedZoneName:
    Description: Hosted ZoneName for Stack
    Type: String
    Default: icumed-lifeshield.com
  parEnvironmentDNSDomain:
    Description: Environment DNS Domain for Stack
    Type: String
    Default: icumed-lifeshield.com
  parCloudFrontACMCertArn:
    Description: ACM for cloud front endpoints
    Type: AWS::SSM::Parameter::Value<String>
  parLogsBucket:
    Description: The S3 bucket where logs (such as FlowLogs and ELBs AccessLogs) are stored
    Type: AWS::SSM::Parameter::Value<String>
  # the format is "/<POD-DOMAIN>/infra/bootstrap/logs/bucket"
  parLogsBucketFolder:
    Description: The prefix or subfolder within the bucket logs
    Type: String
    Default: ""
  parPriceClass:
    Description: Choosing the price class for cloudfront
    Type: String
    Default: PriceClass_All
  parCloudFrontWAFWebACLId:
    Type: AWS::SSM::Parameter::Value<String>

Conditions:
  conEnableLogs: !Not [!Equals [!Ref parLogsBucket, '']]
  conHasLogsBucketFolder: !And
  - !Condition conEnableLogs
  - !Not [!Equals [!Ref parLogsBucketFolder, ""]]
  conDeployWaf: !Not [!Equals [!Ref parCloudFrontWAFWebACLId, '' ]]

Resources:
  resDocsIcumedLifeShieldCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: 'docs.icumed-lifeshield.com'
      DomainValidationOptions:
      - DomainName: 'docs.icumed-lifeshield.com'
        ValidationDomain: 'docs.icumed-lifeshield.com'
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: 'docs.icumed-lifeshield.com'

  resBucketsOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'Origin Access Identity for Pod ${parPodId}'

  # Dummy Empty Bucket
  resDummyBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  resDummyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref resDummyBucket
      PolicyDocument:
        Statement:
          - Sid: "Policy for CloudFront Origin Identity Access for CCP S3 UI Bucket"
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub 'arn:aws:s3:::${resDummyBucket}/*'
            Principal:
              CanonicalUser: !GetAtt resBucketsOriginAccessIdentity.S3CanonicalUserId
          - Sid: BlockNonSSLRequests
            Effect: Deny
            Action: "s3:*"
            Principal: "*"
            Resource: !Sub "arn:aws:s3:::${resDummyBucket}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "false"
  resDummyBucketSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: SSM Parameter containing value of the initial dummy UI S3 bucket name and dns
      Name: !Sub '/${parPodId}/infra/s3/ui/dummy'
      Type: StringList
      # NB: Must use the RegionalDomainName to avoid (307 Temporary Redirect) as it can take up to 24 hours for the bucket name to propagate across all AWS Regions
      #     For more details see https://aws.amazon.com/premiumsupport/knowledge-center/s3-http-307-response/
      Value: !Join [",",[!Ref resDummyBucket, !GetAtt resDummyBucket.RegionalDomainName]]

  resCCPWebDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "${parPodId} - CCP CloudFront Web Distribution"
        Origins:
          # NB: Must use the RegionalDomainName to avoid (307 Temporary Redirect) as it can take up to 24 hours for the bucket name to propagate across all AWS Regions
          #     For more details see https://aws.amazon.com/premiumsupport/knowledge-center/s3-http-307-response/
          - DomainName: !GetAtt resDummyBucket.RegionalDomainName
            Id: !Sub 'S3-ccp.${parEnvironmentDNSDomain}'
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${resBucketsOriginAccessIdentity}"
        Aliases:
          - !Sub '${parEnvironmentDNSDomain}'
          - !Sub 'ccp.${parEnvironmentDNSDomain}'
          - !Sub 'www.${parEnvironmentDNSDomain}'
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: 'false'
          DefaultTTL: '30'
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          MaxTTL: '60'
          MinTTL: '30'
          SmoothStreaming: 'false'
          TargetOriginId: !Sub 'S3-ccp.${parEnvironmentDNSDomain}'
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
        - ErrorCode: '403'
          ResponsePagePath: "/index.html"
          ResponseCode: '404'
          ErrorCachingMinTTL: '30'
        - ErrorCode: '404'
          ResponsePagePath: "/index.html"
          ResponseCode: '404'
          ErrorCachingMinTTL: '30'
        Enabled: 'true'
        HttpVersion: http2
        DefaultRootObject: index.html
        PriceClass: !Ref parPriceClass
        ViewerCertificate:
          AcmCertificateArn: !Ref resDocsIcumedLifeShieldCertificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
        WebACLId:
          !If [conDeployWaf , !Ref parCloudFrontWAFWebACLId, !Ref "AWS::NoValue" ]
        Logging: !If
          - conEnableLogs
          - Bucket: !Sub '${parLogsBucket}.s3.amazonaws.com'
            IncludeCookies: 'true'
            Prefix: !If
              - conHasLogsBucketFolder
              - !Sub "${parLogsBucketFolder}/ccp/"
              - "ccp/"
          - !Ref AWS::NoValue
  resCCPDNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: 'docs.icumed-lifeshield.com.'
      Comment: 'docs.icumed-lifeshield.com'
      Name: 'docs.icumed-lifeshield.com.'
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt 'resCCPWebDistribution.DomainName'

##############################################################################################################################################################
# SSM Parameters
##############################################################################################################################################################
  resBucketsOriginAccessIdentityParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: UI Buckets Origin Access Identity
      Name: !Sub '/${parPodId}/infra/cloudfront/oai'
      Type: String
      Value: !Ref resBucketsOriginAccessIdentity

  resBucketsOriginAccessIdentityUserIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: UI Buckets Origin Access Identity S3 User Id
      Name: !Sub '/${parPodId}/infra/cloudfront/oai/user-id'
      Type: String
      Value: !GetAtt resBucketsOriginAccessIdentity.S3CanonicalUserId

  # distributions
  resCCPWebDistributionParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${parPodId}/infra/cloudfront/distribution/ccp"
      Description: Cloudfront distribution for CCP
      Type: String
      Value: !Ref resCCPWebDistribution

  # endpoints
  resCCPWebUrlParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${parPodId}/infra/endpoints/ui/ccp"
      Description: CCP Web URL
      Type: String
      Value: !Sub "https://${resCCPDNSRecordSet}"
##############################################################################################################################################################

Outputs:
  outBucketsOriginAccessIdentity:
    Description: UI Buckets Origin Access Identity
    Value: !Ref resBucketsOriginAccessIdentity
  outBucketsOriginAccessIdentityUserId:
    Description: UI Buckets Origin Access Identity S3 User Id
    Value: !GetAtt resBucketsOriginAccessIdentity.S3CanonicalUserId
  outDummyBucketName:
    Description: Empty Bucket used as NOP Origin for the Distributions
    Value: !Ref resDummyBucket
  outDummyBucketOrigin:
    Description: Empty Bucket used as NOP Origin for the Distributions
    # NB: Must use the RegionalDomainName to avoid (307 Temporary Redirect) as it can take up to 24 hours for the bucket name to propagate across all AWS Regions
    #     For more details see https://aws.amazon.com/premiumsupport/knowledge-center/s3-http-307-response/
    Value: !GetAtt resDummyBucket.RegionalDomainName
  outCCPWebDistribution:
    Description: Cloudfront distribution for CCP
    Value: !Ref resCCPWebDistribution
  outCCPWebUrl:
    Description: CCP Web URL
    Value: !Sub "https://${resCCPDNSRecordSet}"
  # SSM params
  outBucketsOriginAccessIdentityParam:
    Description: SSM Parameter for UI Buckets Origin Access Identity
    Value: !Ref resBucketsOriginAccessIdentityParam
  outBucketsOriginAccessIdentityUserIdParam:
    Description: SSM Parameter for UI Buckets Origin Access Identity S3 User Id
    Value: !Ref resBucketsOriginAccessIdentityUserIdParam
  outCCPWebDistributionParam:
    Description: SSM Parameter for Cloudfront distribution for CCP
    Value: !Ref resCCPWebDistributionParam
  outCCPWebUrlParam:
    Description: SSM Parameter for CCP Web URL
    Value: !Ref resCCPWebUrlParam
